### ISSUE TITLE
Issues with local copy of master

### ISSUE THREAD

**Issue by VictorVow** [duydl/logseq-calibre-plugin#10]
I'm trying to add a feature to your plugin but I'm having issues with it, I'm not sure what I might be doing wrong as I'm new to Logseq plugin development.

In the console I get these errors when I load the unpacked plugin (using the master branch):
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').

lsplugin.core.js:2 ERROR: [Loader:#logseq-calibre-metadata - logseq-calibre-metadata][16:27:26] loadhandshake Timeout Error: handshake Timeout
    at file:///app/logseq/resources/app/js/lsplugin.core.js:2:88419
```

**Comment by duydl** [comment]
From my experience handshake timeout could happen but the loading would repeat again. Most of the time we could still load the plugin eventually, maybe a reload is required. 

Btw, I am planning to migrate calibre-metadata to calibre-annotation to unify them into one plugin this month. This may affect your work.

**Comment by duydl** [comment]
This is the branch of migration https://github.com/duydl/logseq-calibre-annotation/tree/merge-calibre-metadata . 
If you still have the problem, you may consider make a PR so it would be possible for me to help.

**Comment by duydl** [comment]
Hi. Are you still having issue in the new version? Maybe create a draft PR so I could look at the code also?

**Comment by VictorVow** [comment]
Sorry I ended up stopping work on this, it was an attempt at #9 anyway.
