### ISSUE TITLE
Cannot read PDF format on the right side. Only PDF format can be opened in the browser.

### ISSUE THREAD

**Issue by stelvetica** [duydl/logseq-calibre-plugin#12]

**Comment by duydl** [comment]
Hi. Could you still read epub on the right side or both epub and pdf are not readable.
In any case, I think open pdf on the "left side" with Logseq built-in pdf reader would be better choice as Calibre viewer itself have no annotation support for pdfs.

**Comment by stelvetica** [comment]
谢谢，我可以在左侧阅读epub，提出这个疑问是误认为Calibre 可以支持pdf注释。
尽管我希望能有个阅读器可以同时支持多个格式并自动将注释导出到logseq，看来是很难实现了

**Comment by stelvetica** [comment]
Thanks. I can read epub on the left. I raised this question because I mistakenly thought Calibre could support PDF annotations. Although I hope there can be a reader that can support multiple formats at the same time and automatically export annotations to logseq, it seems difficult to achieve.
