### ISSUE TITLE
Add an option to close the book viewer

### ISSUE THREAD

**Issue by Plexprofile** [duydl/logseq-calibre-plugin#2]
This plugin is base on some interesting concepts but at the moment seems to miss some basic features. It does not support the closing of the book viewer after it's opened, forcing the user to manually terminate logseq process in order to quit the reader mode.

**Comment by duydl** [comment]
You could close the viewer with the red rectangle on the top right. 
I am going to add better styling to it later.

**Comment by Plexprofile** [comment]
There is a styling issue after closing the viewer with red rectangle on the top right

When the viewer is closed, the active editing pane slides automatically toward the right without getting back to the initial position, causing it to overlap with the right sidebar and leaving an area of blank space on the left
![bug](https://github.com/duydl/logseq-calibre-annotation/assets/139643082/ba5f9d98-7f2b-4c9f-b87b-575a6dbcba40)
