### ISSUE TITLE
Can not open the epub book in logseq

### ISSUE THREAD

**Issue by yibie** [duydl/logseq-calibre-plugin#5]
I can search the name of book, but when I click the 'open' button, logseq can not open the book.
It shows "network error. Is the serve running or accessible?"
![image](https://github.com/duydl/logseq-calibre-metadata/assets/365484/9ff99b9f-c571-4afd-880d-cd1fc7646e0a)

But I seted the content sever of Calibre：
![image](https://github.com/duydl/logseq-calibre-metadata/assets/365484/959e1cfc-1e1b-49ae-95a3-ada0baa9d2e7)

Now, I don't know where the problem is. 

At last, thanks for your great work!

**Comment by duydl** [comment]
Try clicking on the Test Server button. It will redirect you to the content server link in the browser, like this: http://127.0.0.1:8081/. Check if you can read books normally that way on the browser. 

If you can, replace the link in the renderer  {{renderer calibreViewer, special, http://localhost:8080/#book_id=24&fmt=epub&library_id=Audio-eBooks&mode=read_book}} {{renderer calibreHighlight, false, 2000, http://localhost:8080, Audio-eBooks, 24, epub}}
with that link.  Also replace the link in the setting of Calibre Metadata. 
![image](https://github.com/duydl/logseq-calibre-metadata/assets/56506156/9e1eea34-0294-429e-bb61-4d13cc239d3e)

If you cannot, we will have to discuss further. It would likely be a problem on Calibre side.

**Comment by yibie** [comment]
I had tryed, but it still show the wrong message:
`Failed to communicate with "//interface-data/init?1697553811876", network error. Is the server running and accessible`

I replace the link in the renderer:

<img width="538" alt="image" src="https://github.com/duydl/logseq-calibre-metadata/assets/365484/5fc2c72e-14df-4e07-9eb3-91f2f26f12ee">

I changed the plugin setting:
![image](https://github.com/duydl/logseq-calibre-metadata/assets/365484/5de6d2a6-761c-45cf-ba6c-11644de7b70e)

Calibre content sever works well, can open books, and read:
<img width="520" alt="image" src="https://github.com/duydl/logseq-calibre-metadata/assets/365484/4d50d9b2-e745-4f04-9709-912462a79cbf">

**Comment by duydl** [comment]
Remove the extra /  after the port in the renderer to open the book and in the setting for later use. Hope that will resolve it. 
There was another user who had an issue stemming from the double slash.

**Comment by yibie** [comment]
It fixed now!

Thanks a lot.
